/** Declaration file generated by dts-gen */

export function createClient(): any;
export namespace device
{
    function create(url: any): any;
}
export namespace ssdp
{
    function create(): any;
}
export namespace utils {
    function getNamespace(data: any, uri: any): any;
}
