/** Declaration file generated by dts-gen */

export class Client {
    constructor(gateway: string);
    close(): void;
    connect(): any;
    externalIp(cb: (error, info) => void): void;
    onclose(): void;
    onerror(err: any): void;
    onlistening(): void;
    onmessage(msg: string | Buffer, rinfo: any, ...args: any[]): any;
    portMapping(opts: any, cb: (error, info) => void): void;
    portUnmapping(opts: any, cb: (error, info) => void): any;
    request(op: any, obj: any, cb: any): void;
}
export const CLIENT_PORT: number;
export const OP_EXTERNAL_IP: number;
export const OP_MAP_TCP: number;
export const OP_MAP_UDP: number;
export const RESULT_CODES: {
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
};
export const SERVER_DELTA: number;
export const SERVER_PORT: number;
export function connect(gateway: string): Client;
